# MONGO-EXPRESS DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        # For Authentication: This is the Username of the Mongo Database referenced from the SECRET file.
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        # For Authentication: This is the password of the Mongo Database referenced from the SECRET file.
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        # Below here we define the MONGO-DB Internal Service's name so that these pods send requests to it.
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url  # Here from the ConfigMap, we reference the Database URL and it's value is the name of the MONGODB Internal Service.

        # we can also use the Internal Service's name directly here without the need of Config Map but it is not recommended because if used at multiple places, we would need to make changes in each and every file.
        
        # env:
        #   - name: ME_CONFIG_MONGODB_SERVER
        #     value: mongodb-service

---
# MONGO-EXPRESS EXTERNAL SERVICE

# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo-express-service
# spec:
#   selector:
#     app: mongo-express
#   type: LoadBalancer
#   ports:
#   - protocol: TCP
#     port: 8081
#     targetPort: 8081
#     nodePort: 30000
